//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPhanMem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAddress
    {
        public int acc_add_id { get; set; }
        public int acc_id { get; set; }
        public string acc_address { get; set; }
        public string acc_phone { get; set; }
        public string acc_username { get; set; }
        public bool isDefault { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
