//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPhanMem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Feedback()
        {
            this.Feedback1 = new HashSet<Feedback>();
        }
    
        public int feedback_id { get; set; }
        public int account_id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> rate_star { get; set; }
        public string status { get; set; }
        public string content { get; set; }
        public Nullable<int> replyfor { get; set; }
        public System.DateTime create_at { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedback1 { get; set; }
        public virtual Feedback Feedback2 { get; set; }
        public virtual Product Product { get; set; }
    }
}
